---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
