---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age14h7cte93kvkt93ekg6yyyfgymgrnxcaqwu2ardcmgudy5anzmchspy67df
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age14h7cte93kvkt93ekg6yyyfgymgrnxcaqwu2ardcmgudy5anzmchspy67df
