---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age18qvemn7j79ajvfdenhn4hs2nxq88f2x59z9ja06ynr2epu8jadgs2x03ct
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age18qvemn7j79ajvfdenhn4hs2nxq88f2x59z9ja06ynr2epu8jadgs2x03ct
