---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1puuvxszxx7c79rzsqf5x4cm5ulhpy22jdes9y09ha96gwh7pkvgqwvgkle
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1puuvxszxx7c79rzsqf5x4cm5ulhpy22jdes9y09ha96gwh7pkvgqwvgkle
