#!/usr/bin/env bash
if ! type "$flux" > /dev/null 2>&1;
then echo not flux
fi
        if  ssh -q -o ConnectTimeout=5 abaddon@88.198.61.240 "ok"; then
            echo SSH into host with username  was successfull
        else
            echo into host  with username was NOT successful, did you copy over your SSH key?
            echo ssh -o ConnectTimeout=5 abaddon@88.198.61.240
        fi
status=$(ssh -q -o StrictHostKeyChecking=no -o ConnectTimeout=5 abaddon@88.198.61.240 echo ok 2>&1)

if [[ $status == ok ]] ; then
  echo auth ok, do something
elif [[ $status == "Permission denied"* ]] ; then
  echo no_auth
else
  echo other_error
  echo $status
fi
