# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rRQKruPLwmfUVwVt83hD44KWEAWoXCUdsM3qmw==,iv:VEOTb4EVCWi+rf+K/uHZQh0I3Kzfys92rJRJusMB8iA=,tag:k+CZpnzB5IVv9eLBgeANGw==,type:str]
    api-key: ENC[AES256_GCM,data:UbcpczRVa2ttTdZa7eonU2qIHxiLXo0qQ9r6YvGCkK5UA7gFSQ==,iv:3/mIbZQiOwWRfGr8Du/XY5POh4JVPiCsdudvgrYk9UM=,tag:s4+1/5Inm+bSgQ12cGmfzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qvemn7j79ajvfdenhn4hs2nxq88f2x59z9ja06ynr2epu8jadgs2x03ct
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c3phS2kzRmlFUGx4anN5
            bDZKalAzMmZrZzJwNzkrVzVRYk1xMzBCT25VCkpveW53Ry9GZm1zMUp6U1ppYksv
            dUNUZ1dXTk9xaURGbHQreUlEQWZ6SjQKLS0tIFlyZnVCTi9ablRvOENKMjZVZEE2
            ZU5VMXgweG5GT25tc2hUalJ4a2dQYzgKbrR3JwvUENn3RNuJZBRfPX/Sj9jU526a
            3xwKDb3pZQYJFPfyV7qNymFc6MW4AgPsB1mTxBme8Ev+IVxsaVXiiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-03T11:27:43Z"
    mac: ENC[AES256_GCM,data:pOOXniI8thYwdfT/M+7fHDFw+J5dSkOPLevGy+9VNH3SqGXgVBHPzPRwtI/evAxOzYlRX4cAaPE7XLFq9kR/2RjZBX6xEguxO1Vq5Ruw/eMFdLeqhLe0U/cS+wOMM5/3tZEOeYE6cNCJK4eEUwGqdGWgGhy3GlFtYqcxDf9KGrY=,iv:6M2N19/UWgOAaiU2USckV4DdBQJSDoZzDd4IWlkk8LY=,tag:lRv3x4o2wPlYVd47xnQ8SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
