# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:7BTAQpmE6ZjKWumfHm4RH5nanx8nifKS05JmMA==,iv:8ySIoArWNORHvc309i4iLp2K/4dGJ8i8MwJT1U7594c=,tag:F+Be2/jmKncwA4jIHu9+TQ==,type:str]
    api-key: ENC[AES256_GCM,data:NZoMwwFooktihLvXUfIifCY6xusK20gKKfhWYlQhaVP6vDhmZQ==,iv:E3F5qEdVa3bW0aMonykC17kmxcDyQWByGCKHHabMuA0=,tag:1kW1t7xJOYSViUIyALrIZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObDNFeGN0MDNSOTFRUDZy
            V3hRaG1vV3Y0c1BxUGp2VjdvVjR4VU1tNEZnCm1mOG0zOTFtajBSdmVORlJZaGwz
            QVFuMThyaHFMUjA2OU5GT0crcno5M00KLS0tIGpqY1BGRUR0aXJUREFmQUFJTXd2
            SnJIenJ1SGZ1WEFmd291V1AzaXZkSm8K6NAsT3+FGfrYocqn358Mon/IhAIFHNg4
            JrhwN4FiTYNY8HsfCvEDGthhXIuw2xnggBvJKME6bN1N+hzmxPPbKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T08:41:54Z"
    mac: ENC[AES256_GCM,data:CI/ccgbGcgGlN/O7aYE919YaepJPtgntrymprFT2SW/R9G7gk4e8kPnUxWXfb7RUjFF1+R9RtDY+V8ReD++P0e9U2YeG1j96UV8Lp1Ir/yvEHGHGDNl+Jb5YOLhEreCldZVS+Uf3S0M1uSU7zBPgz1mSNUegVhVakfZRJgvoY10=,iv:201da4xcIoJMhkGsLdlneFsfdF/EJ06fNeHT2YeHS/A=,tag:NL9spDo8ucST1gL9XvsnWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
