# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hffnwMZ7yN0fbCb72Tyjq+I=,iv:eVRL+UnoccbnwdVmOz2XDBGrPfg8Zu7NBMEk3YdNwrc=,tag:6emhZXmsZEChc28eDgP99A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:u9rAEcucp9vDJuvjN5dhoIARw9y4Y0i58b6UWw==,iv:tunlu23Z/tV1xNCYve/VuhonK4R1yfB746cwo8awdBY=,tag:PoVedCTZ/3hGP0eFg+/FKg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:LSwsbQR92Fjdhf4YGoqawMYahuooNP3qAjDf/bUMqHc0Sw+RYv6s+OKg+6utETCflYc=,iv:yX+HXEZq5jvTWHtXK+n7O6LV3LVh1hiKfG2uSfpdOGo=,tag:AJU+K2ozJoMkdfbUBF1rlw==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Zr+ONSm+uKtqvRDVRg6LXGk7cQ1EoHs0yicmrNTxyTkZsJHDYRkRbSrkyLaqy3N7,iv:eRJ0GMGD9N5UdTv7uQaZu40BmOZiK1eqpKWAQikjuaA=,tag:PBvcrrJD9TAASMMLn0BYYg==,type:str]
    SECRET_MAILGUN_PASSWORD: ENC[AES256_GCM,data:hj4ZsSWrCvACgC+rLcvuzrRDK3DMofc4X2qlY4Ox84qnGW0qRuXJpfUPkvSMhajl/bY=,iv:DwxA4OJ1esKlJygOtppVYPfavw95rIH3BUr/VF9gnc0=,tag:jKF//CkFhgpyLDHDz9npEQ==,type:str]
    MAIN_DOMAIN: ENC[AES256_GCM,data:EWsTrH4A6R8AHsg/WiLlelI=,iv:d40Y09nAcG8/58Vw4nXiEXWIoeaBa/Sd88Y1VYkd31M=,tag:WwMem+5tPqXah/t09Bk+UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQnRKQ21xZTNvYi9PVUU4
            Q1JTd2c4RE1ZdVJXNitxcGpjRURhaWM3OWl3CkpWbGY4THBwQkRRMVlVamE1Yk9x
            SDAvbmJMN0tPWldpaVEvbC8ybXNVS2sKLS0tIEhId2pLeCtkWk1iU2ZBWlA2WE9k
            bHEyZTFQeWRMcHFKZlFzTGtWVVJSbE0K+Xu8zzN+aifw1CRcTpUcpJP/pv25s/OU
            LWn6Q0zLAQNihUjfVBoWa2sTBNQtb23aiq4FmJbT5rU5tKzXB2Ymow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-22T10:42:58Z"
    mac: ENC[AES256_GCM,data:0Hrv3WBls3y9w2MYZWj1X8vylsCX/JXZcUzr1i/p6AdJo2c0q73IwG7JXrlW8iSOVSpN2dn8UhxxdkixVC6IWllcWuyGRYVXXsb3awvoNDG6k7CB8F+hv2gSDq7N6rQfqCI4koS+DeNyY/UHZxmOo8BoVnyz+U3ioAkxyuk9ims=,iv:jZTBIZAe1VGl+oiPt9G1UzehmcaV7zQWGiFb6SYBs1I=,tag:hHMjXM64bJhYUyElI1wOew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
