kind: Secret
ansible_user: ENC[AES256_GCM,data:t7Al62PlTQ==,iv:+RMIh7QwdKuGSCrAjiX8NWV/7gU9OMoP+SPF1u95Frg=,tag:r/zAi+u0D+Hv8GTcgOLteg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GS8Uoiyvsl07zmYY8LIwQw==,iv:tYuolNfIhlvgV3u6wWJUQDbMziyhJYeJ9z9VinqUJUY=,tag:o2HHdgglrJSCbQoEadDjWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV0NGSDBJMFlOYnRNSFpK
            d2xwQlNudGQ0cEIyVGJxQ1JqdmhuNnVQNmdnCnBKT2xabDRtRTRmZ1lOVEh2cmwy
            OUtCS1p6LzllRk9qbUUwTW4ybDlHREEKLS0tIEVuR0wzK1IvcGRpRUM2aDJPMGlJ
            aXRWc0owcDZpOVVOdDdBUHpSQ3NjZGcKLkuoSnUhGTUT9j7L/WdnHuvKlfhCjV9s
            aXWKM5+YZ3knyQe4PZxgPsSGYobqDZscfbyb+Ntiwu7tySsCQFbEJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T08:41:54Z"
    mac: ENC[AES256_GCM,data:0n5Gk/9gbSh7gREjZV/QKAY5tmMW77D5jW0ctFh3+a3kWk1wgtaz5epWm9APXDuVAy7aHv8sv8yqVShDiKpN/mkZR3xwH/KW30Navy+bFb4ec0dKfz11BAEURmghB4yjVZBs11hwx4nAsFFuqOAL6VyvrwwKwgnH5jtNyFCQOZc=,iv:vN+M3wferuFmWzUotYmu5yI7kKaDNt5yemvOrrOE22Q=,tag:13n5w+nnvj49iv/frTYleA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
