kind: Secret
ansible_user: ENC[AES256_GCM,data:pTsCrk4c+w==,iv:d4SXlYEtV4ak7IOCUOLmqfDRKDUSguoAirZ7y6U4Otk=,tag:PjWB2Cgj7pjLLtxUM60s6g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:KfMRvwm0Q1D2PjLHLb+dkA==,iv:aBDeyfJgsqiFbAQfjuCUY6Bgp4M6H7u7PRcnbkXmXhY=,tag:7hfC5LdIFyLfL3Q2MbLCAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puuvxszxx7c79rzsqf5x4cm5ulhpy22jdes9y09ha96gwh7pkvgqwvgkle
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldGpCbGZubktzWjNqTE9B
            dTFtakU0LzJvdzR2NVEvdVZvMnIvVTljNUFZCkloK3Q3Wmk5MGQvR25YSzl0b3Y2
            ZGtDb1J4d2k5MGR2Z0Qya3NZUzJ3dEEKLS0tIExwdWJGSzEya3dQa2pXNmFSTzgw
            MGlMWGNQdVA5VUJBbFVnZ3BhTW9vdFEKMBLLjj4djwAVBg3v6Qj347q5ulIRNDY/
            0RVd2oLn4bokVA6XYNNvvc8dVHPvkxJORrzC6qQVqE9gzDrdmL6v/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T08:26:21Z"
    mac: ENC[AES256_GCM,data:mZ5bQeblhsvEkpojSkJHXMO3WQS2buXp+6tPJ4HYrqkBik6zkaKLG8jR2u2rQtOmAmgUF8CsAG5Ugz4bJNZGbee3lNEk3E6t6+j0rRj2FODbOeTYXOugMVvbRgj/t30jnrSfBpM+IIBYGHWgLATSkpgO9qmgN55xxG8yje4K+TA=,iv:sMjUSQ0C8b23xc4UyZ/Q6W/FXDs5NNmYYxDBCwUvV/o=,tag:2yrA5i4a8CGrfKPglXbbfg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
