---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.2.16-10.0.2.27
  METALLB_K8S_GATEWAY_ADDR: 10.0.2.16
  METALLB_TRAEFIK_ADDR: 10.0.2.27
