# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bsxLvShbjv0MR4KK0w7pKU8=,iv:LzCNYSFMeVzzyyZVYYW729jOw2CuhTy8th+uyhyNzUE=,tag:IW+QZJrKH+Jiw0sPowpK5g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tNAs3ACmJ6I+vVrJedj+ToJYbJVoopWBVJYa6g==,iv:KYAWcOqIQcim6AUhI4YSz8WTBhek9I5zdXIuy4v4rLg=,tag:xu7nhQUg2yVXO4E/Bm0Gyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14h7cte93kvkt93ekg6yyyfgymgrnxcaqwu2ardcmgudy5anzmchspy67df
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTHFJZmN3YysydmpRZlJM
            SUFCOE4xV1NENDh0d05FRnNTbE93em1tSEdvCldZMWxabkpKalJsU3dQUkt0Ulho
            a2J4aDIwUmNIOGZ6TG5VdzZ3d0VjdUEKLS0tIHhwZWlTQUxlNmllaHo2S3pmckZZ
            eVVJeEpqMjZiY3BDWFBPczFSYUd0ZlUKBRT7SpEq+vc1w8YF6lX9C9XmEanxi4RP
            8VFuQthHlbbDR/g4hERDPE6bBLEn7Pv+Ns/NfCrelCSsNP1XxGbSZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T07:01:19Z"
    mac: ENC[AES256_GCM,data:SaO2uFLsBb9PBOwFmlIGLHP/ZFu84i2CtDi5YVWkpLwvleafF/0TZtHoO8PRqFOgF+uiFsnZqd95LTAvKgZf2ySlGsxdkrJWfufPkaeY56EZ5xhmYnRL/RVbMte7uoiEG5ea3DKHhhMSaxzH6TuA3OL/N7UIY5jyzjfQSTq3/Ng=,iv:vuAPHS5yAwoSmriooip6NgT1T1OvY5M+UYJUO+UN7V4=,tag:nmqhfHo5ptKp5YafGwhXiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
