---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE:
  METALLB_K8S_GATEWAY_ADDR: 88.198.61.240
  METALLB_TRAEFIK_ADDR: 88.198.61.240
