# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ndRXNEZGtHku9ypLZdROBFqeoEhxJfCYbCP+8bvFklSSpGvuhpgFEA==,iv:E3UUpMEY3rsVYlH5MOLjgXLqI40qEsFaAQDLxTCllzE=,tag:Mm99OoXaOKYYNW3jAb5j/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlJYWW5JWjh1M2k3Vk1s
            ZjZEaWVrSEJlZ29uS2hUWWNrc1oxTlVDUERJClJlelJ4ZEF3a0piMGsrRzZBd0NN
            d0Y1ZTQyUjIvUG0rSXZkVWYzRlhGNmMKLS0tIHF1RkZVL2tZNVFWd2lUSlBkRzFv
            Q05NY0JqbHpwdGFpbXNxT3I5dDhUVzQKbEVwdHTpSWRaXBjnW8ouzPZYKB3fq+2g
            ISy8pABT/+W6oxq52/NFKJpthF1HYN+9uqpp/sK2R54q9yYSE5iHDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T11:02:13Z"
    mac: ENC[AES256_GCM,data:izhi1lgEmOqw9XXq2AkO5i7kg+tfmWaYzNB2lhjA4uOL6SqHDmPUZeb8pVTGkP7CAa9DTOx3B/TL1zCKNdlSztAYTNUu1ZHw66M2Neo4KmJ42YRajm2MyXpFwijhGeAof9wHyxTWvve+lMRlI5GpoWgEUicg4ubkhCOgJJDWU1I=,iv:WlfrhRbbQvD8LPGAjz0JiN5J40BasnUtYEt2F5Jha+w=,tag:1eGHYqtlYhYHsQx5R3lQ5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
