# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:I7QVFhhbYcGxfcHDakh3NTftEDoPnXpuCOOzJMjynm8uSoTuOg==,iv:RTCDoQzxY7x7F2xgzv3oFqYqyacLTlLjo/SumUvip5Q=,tag:1fAsVyKpINOLsndKlfSuHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1puuvxszxx7c79rzsqf5x4cm5ulhpy22jdes9y09ha96gwh7pkvgqwvgkle
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeThCb3dicnRsYmg4d1FZ
            NjdubzJYd0hPejl5TjFUZUUwRjRjVlpCbGhFCjFGU2duUGZoRVdYdS9KR1NLT0Rh
            a1NUOW1RYWREZmhzMXNRU0NRVGpCUEUKLS0tIEwxSjR3UTNsRzNiMGluM2I3L3FZ
            RHp2ZVMyYkRhaGJadEs4ak1hMVg2dGcKp8aJ1dZSZnd8BDZ2BjObMfc3oDlrqpS1
            oNHfcJXgju4UAG2LBnDiPS/ynEuLv4vQj2vmmCBi9i96xzM8DxdA7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T08:26:21Z"
    mac: ENC[AES256_GCM,data:rg+jM0UCZCv/MPmlF/rk/DpGsIYzwAgleclm0JLt+3/SavPuVLDQ/Lfyd49nu/ISP42mm74uqIw3b3GRWHVC76Id+oA/x8YigYAgYrsLunmP5MHmZAZla2AYKLf4Ly9xS6PgkZ/dVae6EdC19E71iSNCJqGDV6H51d1BeR8uYdw=,iv:ee8JcFazOzx9ebZvXCB+YN04XC/fgtd/jWExeaZnh/8=,tag:5QLfj+AhrAScQXzLqZHVNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
