# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:F3SpXIYyiS9f3PhzWQyt85OD4fWaFb7WXL4pQR4xJ37IjB/SUA==,iv:PVQtoYv4lmM70ZqXIRDrC93qZIrMBkBE+IWmcgs5wOY=,tag:Jd69jqbqs0xfSqimLkZafg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kadx6kwm2mtd7rf4tmer0ugnnj4lxtrvmnuv8m2a94hktw9cq3qq05ugw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUV0a1krOW1pWXB5Qncy
            RThqNFFGVVJJVzl5NERnTFM1Ui9XZDY4SWowCjZVbUJoL2lXNFBvZmpXUm9DdEhY
            ZFhiQ3Jva2dHSmRhTnQ3VmgwaUpuK3cKLS0tIDdnWk9nMTlnam9mVDVjOHQzcVBs
            SVVpTGEwRXVBeGZhVzBacWNTQjU4bVEKDeBa1BtBZ4dM5fPwgKuZv9wInqRMbzgb
            boYWO9evD8mls4AqBYJ0B1cqj2A3L+YAbxru19DQkkQLoaH6dCmmBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-16T08:41:54Z"
    mac: ENC[AES256_GCM,data:L6+Uf45D9j6/UWk4TmmaAEEqxhtXnRdVQzBl4kjgxUg3+0un8Yzvrc/9qJtxlbR7YaAop+LkJkfBmiVC7ierhWvHuXw09ieD/PQ7nBmkmD2DIR1iyeMEtAba98BIRTdTLJsi04z8UFhGuV7jOnSv2o82fmQEKHgNKFCptDXwyiw=,iv:VseTtWIz9QqRwQdqpEwZXnQMpf5LyKiZiFDtPFwbiUk=,tag:sfq65yJcEdvP22rXNkkcfA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
